apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: mysql-pass
  literals:
  - password=password

resources:
  - nginx.yaml
  - mysql.yaml
  - wordpress.yaml
  - phpmyadmin.yaml
