apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: ft_services
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: ft_services
    tier: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: ft_services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
      tier: phpmyadmin
  template:
    metadata:
      labels:
        app: ft_services
        tier: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: my_phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 5000
